services:
  db:
    image: mariadb:11.4.2-ubi9
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASS: pass
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: parts_unlimited
    volumes:
      - parts-volume:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
        start_period: 1m 
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
    command: bash -c "python manage.py migrate && python manage.py runserver 0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  parts-volume:
